### ISSUE TITLE
Вопрос от Travelpayouts :)

### ISSUE THREAD

**Issue by EngExp** [vladbalmos/travelpsdk#1]
Здравствуйте, Влад.

Меня зовут Егор, я технический писатель в Travelpayouts. Пишу статью для справочного центра о разных наработках, сделанных с помощью нашего API.

Если Вы не против, я опубликую там ссылку на Ваш код https://github.com/vladbalmos/travelpsdk/. Буду признателен, если найдете пару минут и напишете в двух словах, что он делает и как его использовать. Это существенно ускорит мою работу.

Хорошей недели.
## 

Abramenko Egor
Technical Writer
egor.abramenko@aviasales.ru

**Comment by vladbalmos** [comment]
Hi Egor,

Unfortunately I do not read Russian and google translate wasn't of much help. Can you report the issue in English?

Thank you,
Vlad Balmos

**Comment by EngExp** [comment]
Hi, Vlad

I'm a technical writer in Travelpayouts. And I'm going to create an article about libraries that help to work with our API. 
Could you tell me what your travelpsdk does and whether I can publish the link to this repository in the article?

## 

Best regards,
Egor Abramenko

**Comment by vladbalmos** [comment]
Hi Egor,

TravelPSDK is an SDK that interacts with the Travelpayouts Flight Search API. It can do basic flight searches based origin/destination, number of passengers, date of departure & arrival and trip class. Although the software is functional I consider it alpha quality. 

You can of course post links to the repository. Unfortunately I won't be providing any documentation. Anyone interested in using it can read the tests and the source code which are pretty self explanatory.

Hope I was able to help you,
Regards,
Vlad Balmos

**Comment by EngExp** [comment]
Hi, Vlad

Thank you!

## 

Best regards,
Egor Abramenko
